<?php

namespace Proxies\__CG__\BabySitter\BabySitterBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \BabySitter\BabySitterBundle\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'iduser', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'dateDeNaissance', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'email', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'adresse', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'numeroTel', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'codePostal', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'type', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'fax', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'nationalite', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'sex', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'photo', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'profession', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'nbaime', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'nbrsignal');
        }

        return array('__isInitialized__', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'iduser', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'dateDeNaissance', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'email', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'adresse', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'numeroTel', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'codePostal', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'type', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'fax', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'nationalite', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'sex', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'photo', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'profession', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'nbaime', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Utilisateur' . "\0" . 'nbrsignal');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIduser()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIduser();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduser', array());

        return parent::getIduser();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance($dateDeNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', array($dateDeNaissance));

        return parent::setDateDeNaissance($dateDeNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', array());

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroTel($numeroTel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroTel', array($numeroTel));

        return parent::setNumeroTel($numeroTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTel', array());

        return parent::getNumeroTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', array($codePostal));

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', array());

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationalite($nationalite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationalite', array($nationalite));

        return parent::setNationalite($nationalite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationalite', array());

        return parent::getNationalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', array($sex));

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', array());

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', array($photo));

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', array());

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession($profession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', array($profession));

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', array());

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbaime($nbaime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbaime', array($nbaime));

        return parent::setNbaime($nbaime);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbaime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbaime', array());

        return parent::getNbaime();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrsignal($nbrsignal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrsignal', array($nbrsignal));

        return parent::setNbrsignal($nbrsignal);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrsignal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrsignal', array());

        return parent::getNbrsignal();
    }

}
