<?php

namespace Proxies\__CG__\BabySitter\BabySitterBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offre extends \BabySitter\BabySitterBundle\Entity\Offre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'idOffre', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'titreOffre', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'nbrEnfant', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'ageEnfant', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'description', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'typePlanification', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'dateDebutOffre', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'dateFinOffre', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'tarif', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'offreDate', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'iduser', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'idQualite', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'idResponsabbilite');
        }

        return array('__isInitialized__', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'idOffre', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'titreOffre', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'nbrEnfant', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'ageEnfant', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'description', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'typePlanification', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'dateDebutOffre', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'dateFinOffre', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'tarif', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'offreDate', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'iduser', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'idQualite', '' . "\0" . 'BabySitter\\BabySitterBundle\\Entity\\Offre' . "\0" . 'idResponsabbilite');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Offre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOffre()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOffre();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOffre', array());

        return parent::getIdOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreOffre($titreOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreOffre', array($titreOffre));

        return parent::setTitreOffre($titreOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreOffre', array());

        return parent::getTitreOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrEnfant($nbrEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrEnfant', array($nbrEnfant));

        return parent::setNbrEnfant($nbrEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrEnfant', array());

        return parent::getNbrEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgeEnfant($ageEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgeEnfant', array($ageEnfant));

        return parent::setAgeEnfant($ageEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgeEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgeEnfant', array());

        return parent::getAgeEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypePlanification($typePlanification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypePlanification', array($typePlanification));

        return parent::setTypePlanification($typePlanification);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypePlanification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypePlanification', array());

        return parent::getTypePlanification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebutOffre($dateDebutOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebutOffre', array($dateDebutOffre));

        return parent::setDateDebutOffre($dateDebutOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebutOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebutOffre', array());

        return parent::getDateDebutOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinOffre($dateFinOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinOffre', array($dateFinOffre));

        return parent::setDateFinOffre($dateFinOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinOffre', array());

        return parent::getDateFinOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarif($tarif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarif', array($tarif));

        return parent::setTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarif', array());

        return parent::getTarif();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffreDate($offreDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffreDate', array($offreDate));

        return parent::setOffreDate($offreDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffreDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffreDate', array());

        return parent::getOffreDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIduser(\BabySitter\BabySitterBundle\Entity\Utilisateur $iduser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIduser', array($iduser));

        return parent::setIduser($iduser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIduser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduser', array());

        return parent::getIduser();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdQualite(\BabySitter\BabySitterBundle\Entity\Qualite $idQualite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdQualite', array($idQualite));

        return parent::addIdQualite($idQualite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdQualite(\BabySitter\BabySitterBundle\Entity\Qualite $idQualite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdQualite', array($idQualite));

        return parent::removeIdQualite($idQualite);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdQualite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdQualite', array());

        return parent::getIdQualite();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdResponsabbilite(\BabySitter\BabySitterBundle\Entity\Responsabilite $idResponsabbilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdResponsabbilite', array($idResponsabbilite));

        return parent::addIdResponsabbilite($idResponsabbilite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdResponsabbilite(\BabySitter\BabySitterBundle\Entity\Responsabilite $idResponsabbilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdResponsabbilite', array($idResponsabbilite));

        return parent::removeIdResponsabbilite($idResponsabbilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdResponsabbilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdResponsabbilite', array());

        return parent::getIdResponsabbilite();
    }

}
